"""Generate a submission-ready Markdown report from scenario metrics."""

from __future__ import annotations

from pathlib import Path

from .metrics import MetricsReport


def render_report(metrics: MetricsReport) -> str:
    """Render a complete lab report from metrics data.

    Generate a report that includes:
    1. Metrics summary table (total scenarios, success rate, retries, interrupts)
    2. Per-scenario results table
    3. Architecture explanation (your graph design, state schema, reducers)
    4. Failure analysis (at least two failure modes you considered)
    5. Improvement plan

    Use reports/lab_report_template.md as your guide.

    Return: formatted markdown string
    """
    summary_rows = [
        ("Total scenarios", str(metrics.total_scenarios)),
        ("Success rate", f"{metrics.success_rate:.1%}"),
        ("Average nodes visited", f"{metrics.avg_nodes_visited:.2f}"),
        ("Total retries", str(metrics.total_retries)),
        ("Approval/HITL visits", str(metrics.total_interrupts)),
        ("Checkpoint history verified", "yes" if metrics.resume_success else "no"),
    ]
    summary = "\n".join(f"| {name} | {value} |" for name, value in summary_rows)
    scenario_row = (
        "| "
        + " | ".join(
            [
                "{id}",
                "{expected}",
                "{actual}",
                "{success}",
                "{retries}",
                "{interrupts}",
                "{latency}",
            ]
        )
        + " |"
    )
    scenarios = "\n".join(
        scenario_row.format(
            id=item.scenario_id,
            expected=item.expected_route,
            actual=item.actual_route or "—",
            success="PASS" if item.success else "FAIL",
            retries=item.retry_count,
            interrupts=item.interrupt_count,
            latency=item.latency_ms,
        )
        for item in metrics.scenario_metrics
    )
    failures = [item for item in metrics.scenario_metrics if not item.success]
    failure_summary = (
        "No sample scenario failed. The design still handles the production "
        "failure modes below explicitly:"
        if not failures
        else "Failed scenarios: " + ", ".join(item.scenario_id for item in failures) + "."
    )
    return f"""# Day 08 Lab Report

## 1. Student

- Name: Nguyễn Xuân Hùng
- Repository: `Track3-DAY23-NguyenXuanHung-2A202601640`
- Date: 2026-08-25

## 2. Architecture

The compiled `StateGraph` follows `START → intake → classify` and then branches into
simple answer, tool/evaluation, clarification, risky approval, or bounded retry flows.
Every branch converges at `finalize → END`. Classification uses structured LLM output;
answers are generated by an LLM grounded in the query, tool results, and approval state.

## 3. State schema and reducers

Scalar decisions (`route`, `attempt`, `evaluation_result`, `approval`, and final output)
use overwrite semantics. `messages`, `tool_results`, `errors`, and `events` use the
append reducer, preserving a serializable audit trail in checkpoints.

## 4. Metrics summary

| Metric | Value |
|---|---:|
{summary}

## 5. Scenario results

| Scenario | Expected | Actual | Result | Retries | HITL visits | Latency (ms) |
|---|---|---|---:|---:|---:|---:|
{scenarios}

## 6. Failure analysis

{failure_summary}

1. Transient tool failures are detected by `evaluate`; retries increment an explicit
   counter and `route_after_retry` sends exhausted work to `dead_letter`, preventing loops.
2. Risky actions cannot execute before `approval`. CI uses a visible mock reviewer, while
   `LANGGRAPH_INTERRUPT=true` pauses the graph for a real external decision and resume.
3. Empty or provider-failed LLM responses raise visible errors rather than silently
   fabricating a route or answer.

## 7. Persistence and recovery evidence

Each scenario has a stable, unique `thread_id`. The run checks `get_state_history()` after
execution and reports the result above. The SQLite adapter uses WAL mode and can retain the
same history across process restarts via `outputs/checkpoints.sqlite`.

## 8. Extension work

- SQLite checkpointer with WAL and thread-safe connection settings.
- Real LangGraph `interrupt()` approval path behind `LANGGRAPH_INTERRUPT=true`.
- Checkpoint history verification and per-scenario wall-clock latency metrics.
- Mermaid graph source can be exported from the compiled graph for demo evidence.

## 9. Improvement plan

Next, replace the mock tool with authenticated idempotent adapters, add policy-based
reviewer authorization, distributed tracing, provider retries/circuit breakers, and a
Streamlit approval UI that resumes interrupted threads.
"""


def write_report(metrics: MetricsReport, output_path: str | Path) -> None:
    """Write the rendered report to a file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(metrics), encoding="utf-8")
